import type { CSSProperties } from "react";
import { getUiFontStack } from "@/ui/shellTheme";
import { v3OverlayMediaFilter } from "./v3ThemeBackground";
import type { V3ThemeState } from "./v3Theme";

/** Build CSS custom properties for inline use on a subtree (editor page, etc.). */
export function v3ThemeInlineVars(theme: V3ThemeState): CSSProperties {
  const {
    shell,
    topBar,
    editor,
    scriptList,
    aiSidebar,
    aiOverlay,
    scriptHub,
    actionBar,
    icons,
    settingsChrome,
    accent,
    overlay,
    typography,
  } = theme;
  const mediaFilter = v3OverlayMediaFilter(overlay);
  const vars: Record<string, string> = {
    "--v3-shell-window-bg": shell.windowBg,
    "--v3-shell-border": shell.shellBorder,
    "--v3-shell-edge-shadow": shell.edgeShadow,
    "--v3-shell-page-bg": shell.pageBg,
    "--v3-shell-content-bg": shell.contentBg,
    "--v3-shell-corner-radius": `${shell.cornerRadiusPx}px`,
    "--v3-topbar-bg": topBar.bg,
    "--v3-topbar-text": topBar.text,
    "--v3-topbar-muted": topBar.mutedText,
    "--v3-topbar-nav-icon": topBar.navIcon,
    "--v3-topbar-nav-underline": topBar.navActiveUnderline,
    "--v3-editor-work-bg": editor.workAreaBg,
    "--v3-editor-tabbar-bg": editor.tabBarBg,
    "--v3-editor-tab-inactive": editor.tabInactiveBg,
    "--v3-editor-tab-active": editor.tabActiveBg,
    "--v3-editor-tab-text": editor.tabText,
    "--v3-editor-tab-border": editor.tabBorder,
    "--v3-script-section-bg": scriptList.sectionHeaderBg,
    "--v3-script-section-text": scriptList.sectionHeaderText,
    "--v3-script-section-icon": scriptList.sectionIcon,
    "--v3-script-search-bg": scriptList.searchBg,
    "--v3-script-search-placeholder": scriptList.searchPlaceholder,
    "--v3-script-row-text": scriptList.rowText,
    "--v3-script-row-hover": scriptList.rowHoverBg,
    "--v3-script-row-muted": scriptList.rowMutedText,
    "--v3-ai-panel-bg": aiSidebar.panelBg,
    "--v3-ai-panel-border": aiSidebar.panelBorder,
    "--v3-ai-header-bg": aiSidebar.headerBg,
    "--v3-ai-header-text": aiSidebar.headerText,
    "--v3-ai-header-muted": aiSidebar.headerMuted,
    "--v3-ai-message-user-bg": aiSidebar.messageUserBg,
    "--v3-ai-message-assistant-bg": aiSidebar.messageAssistantBg,
    "--v3-ai-message-border": aiSidebar.messageBorder,
    "--v3-ai-input-bg": aiSidebar.inputBg,
    "--v3-ai-input-text": aiSidebar.inputText,
    "--v3-ai-input-placeholder": aiSidebar.inputPlaceholder,
    "--v3-ai-icon-muted": aiSidebar.iconMuted,
    "--v3-ai-accent-text": aiSidebar.accentText,
    "--v3-ai-warning-bg": aiSidebar.warningBg,
    "--v3-ai-warning-text": aiSidebar.warningText,
    "--v3-ai-error-text": aiSidebar.errorText,
    "--v3-ai-overlay-panel-bg": aiOverlay.panelBg,
    "--v3-ai-overlay-panel-border": aiOverlay.panelBorder,
    "--v3-ai-overlay-header-text": aiOverlay.headerText,
    "--v3-ai-overlay-button-bg": aiOverlay.buttonBg,
    "--v3-ai-overlay-button-text": aiOverlay.buttonText,
    "--v3-ai-overlay-accept-bg": aiOverlay.acceptBg,
    "--v3-ai-overlay-accept-text": aiOverlay.acceptText,
    "--v3-ai-overlay-highlight-bg": aiOverlay.highlightBg,
    "--v3-ai-overlay-highlight-active-bg": aiOverlay.highlightActiveBg,
    "--v3-ai-overlay-highlight-line-bg": aiOverlay.highlightLineBg,
    "--v3-ai-overlay-diff-zone-bg": aiOverlay.diffZoneBg,
    "--v3-ai-overlay-diff-zone-border": aiOverlay.diffZoneBorder,
    "--v3-ai-overlay-diff-removed-text": aiOverlay.diffRemovedText,
    "--v3-ai-overlay-diff-added-text": aiOverlay.diffAddedText,
    "--v3-scripthub-search-bg": scriptHub.searchBg,
    "--v3-scripthub-search-border": scriptHub.searchBorder,
    "--v3-scripthub-search-text": scriptHub.searchText,
    "--v3-scripthub-search-placeholder": scriptHub.searchPlaceholder,
    "--v3-scripthub-toggle-divider": scriptHub.toggleDivider,
    "--v3-scripthub-toggle-indicator": scriptHub.toggleIndicator,
    "--v3-scripthub-toggle-active-text": scriptHub.toggleActiveText,
    "--v3-scripthub-toggle-inactive-text": scriptHub.toggleInactiveText,
    "--v3-scripthub-card-glass-bg": scriptHub.cardGlassBg,
    "--v3-scripthub-card-glass-border": scriptHub.cardGlassBorder,
    "--v3-scripthub-card-scrim": scriptHub.cardScrimFrom,
    "--v3-scripthub-card-title": scriptHub.cardTitleText,
    "--v3-scripthub-card-subtitle": scriptHub.cardSubtitleText,
    "--v3-scripthub-card-shadow": scriptHub.cardShadow,
    "--v3-scripthub-card-execute-bg": scriptHub.cardExecuteBg,
    "--v3-scripthub-card-execute-disabled-bg": scriptHub.cardExecuteDisabledBg,
    "--v3-scripthub-card-icon-btn-bg": scriptHub.cardIconBtnBg,
    "--v3-scripthub-status-text": scriptHub.statusText,
    "--v3-scripthub-error-text": scriptHub.errorText,
    "--v3-scripthub-pagination-text": scriptHub.paginationText,
    "--v3-actionbar-bg": actionBar.barBg,
    "--v3-actionbar-btn-bg": actionBar.buttonBg,
    "--v3-actionbar-btn-border": actionBar.buttonBorder,
    "--v3-actionbar-btn-hover": actionBar.buttonHover,
    "--v3-actionbar-btn-text": actionBar.buttonText,
    "--v3-actionbar-btn-icon": actionBar.buttonIcon,
    "--v3-actionbar-btn-disabled-bg": actionBar.buttonDisabledBg,
    "--v3-actionbar-btn-disabled-text": actionBar.buttonDisabledText,
    "--v3-actionbar-btn-disabled-icon": actionBar.buttonDisabledIcon,
    "--v3-actionbar-attach-on": actionBar.attachIndicatorOn,
    "--v3-actionbar-attach-off": actionBar.attachIndicatorOff,
    "--v3-icon-color": icons.color,
    "--v3-icon-muted": icons.muted,
    "--v3-settings-section-bg": settingsChrome.sectionHeaderBg,
    "--v3-settings-label": settingsChrome.labelText,
    "--v3-settings-desc": settingsChrome.descriptionText,
    "--v3-settings-checkbox-on": settingsChrome.checkboxOn,
    "--v3-settings-checkbox-off": settingsChrome.checkboxOff,
    "--v3-settings-sidebar-active": settingsChrome.sidebarActiveBg,
    "--v3-settings-sidebar-accent": settingsChrome.sidebarAccent,
    "--v3-settings-control-bg": settingsChrome.controlBg,
    "--v3-settings-control-border": settingsChrome.controlBorder,
    "--v3-settings-control-hover": settingsChrome.controlHoverBg,
    "--v3-settings-control-text": settingsChrome.controlText,
    "--v3-settings-field-bg": settingsChrome.fieldBg,
    "--v3-settings-field-border": settingsChrome.fieldBorder,
    "--v3-settings-sidebar-icon": settingsChrome.sidebarIcon,
    "--v3-settings-chip-selected-border": settingsChrome.chipSelectedBorder,
    "--v3-accent-primary": accent.primary,
    "--v3-accent-muted": accent.primaryMuted,
    "--v3-accent-selection-border": accent.selectionBorder,
    "--v3-accent-focus-ring": accent.focusRing,
    "--v3-overlay-opacity": String(overlay.opacity),
    "--v3-overlay-blur": `${overlay.blurPx}px`,
    "--v3-overlay-mode": overlay.mode,
    "--v3-overlay-position": `${overlay.position.x}% ${overlay.position.y}%`,
    "--v3-overlay-media-filter": mediaFilter ?? "none",
    "--v3-page-scrim-opacity": String(overlay.pageScrimOpacity),
  };
  if (typography.uiFontSizeStep > 0) {
    vars["--v3-ui-font-step"] = `${typography.uiFontSizeStep}px`;
  }
  return vars as CSSProperties;
}

/** Apply all V3 theme tokens as CSS custom properties on `:root`. */
export function applyV3ThemeToDocument(theme: V3ThemeState): void {
  const root = document.documentElement;
  const vars = v3ThemeInlineVars(theme);
  for (const [key, value] of Object.entries(vars)) {
    if (key.startsWith("--")) root.style.setProperty(key, value);
  }
  root.style.fontFamily = getUiFontStack(theme.typography.uiFontId);
  const step = theme.typography.uiFontSizeStep;
  if (step <= 0) root.style.removeProperty("--v3-ui-font-step");
}
